### ISSUE TITLE
Decide on C++ Zarr library backend 

### ISSUE THREAD

**Issue by thewtex** [InsightSoftwareConsortium/ITKIOZ5#3]
Options:

- [z5](https://github.com/constantinpape/z5) 
- [xtensor-zarr](https://github.com/xtensor-stack/xtensor-zarr)
- [FastLoader](https://github.com/usnistgov/FastLoader)
- [NCZarr](https://www.unidata.ucar.edu/blogs/developer/entry/overview-of-zarr-support-in)

Criteria:

1. Build dependencies
2. Maintainability
2. Local and cloud support
3. Performance
4. Codec support

**Comment by thewtex** [comment]
CC @lassoan

**Comment by dzenanz** [comment]
Choosing `xtensor`.
